### PR TITLE
Fixed broken link in docs

### PR DESCRIPTION
**Pull request by timmattison**
Fixed a broken link to the class that shows the three byte integer parsing example.

BTW, is there an easier way to do this?  I have several values that are 22, 23, or 24 bit integers that are not neatly aligned to byte boundaries.  I want to be able to read them with minimal configuration and custom code.  I think I understand how to do this with values that are less than 8 bits but not with more than 8 bits.

### CODE REVIEW

**Comment by raydac** [comment]
you can just make custom type processor like int24 int22 int23, [take a look at example]( https://github.com/raydac/java-binary-block-parser/blob/ca3157ba5817fdd592df01e98bc5b4486b4d216d/jbbp/src/test/java/com/igormaznitsa/jbbp/it/CustomThreeByteIntegerTypeTest.java#L135)

**Comment by timmattison** [comment]
I was looking for a more generic solution so that I don't have to create a new class for each different integer size.  I want to be able to use the DSL builder and if I use custom types I think I lose that as well.

**Comment by raydac** [comment]
it is interesting idea to add way to mark and custom field types through annotation as minimum for DSL builder, I will think how to implement

**Comment by raydac** [comment]
I have added DslBinCustom annotation which provides way to mark custom typed fields for JBBPDslBuilder

**Pull request merged**
